# Generated by Django 2.1.8 on 2019-05-16 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
    ]
